version: '3'
services:
  api:
    image: 'johnmcdnl/flashcards-api'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5800:5800

  db:
    image: 'mongo:3'
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

volumes:
  mongo: