ARG node_version=latest
ARG nginx_version=latest

FROM node:${node_version} as builder
WORKDIR /usr/src/flashcards

COPY package.json .
RUN yarn install
COPY . .
RUN yarn build

FROM nginx:${nginx_version}
COPY --from=builder /usr/src/flashcards/build /usr/share/nginx/html
